error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:3306 {"name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":"ECONNREFUSED","fatal":true,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":"ECONNREFUSED","fatal":true,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at new ConnectionRefusedError (/home/user/demoProject/node_modules/sequelize/src/errors/connection/connection-refused-error.ts:8:5)\n    at ConnectionManager.connect (/home/user/demoProject/node_modules/sequelize/src/dialects/mysql/connection-manager.js:116:17)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2024-07-10T08:32:05.370Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:38:13.018Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:38:13.420Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:40:12.836Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:40:12.879Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:44:11.141Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:44:11.185Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:48:16.478Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:48:16.525Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:48:27.540Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:48:27.587Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:51:23.187Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:51:23.270Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:56:32.018Z"}
error: Could not connect to the database. database "exppost" does not exist {"name":"SequelizeConnectionError","original":{"code":"3D000","file":"postinit.c","length":93,"line":"1019","name":"error","routine":"InitPostgres","severity":"FATAL"},"parent":{"code":"3D000","file":"postinit.c","length":93,"line":"1019","name":"error","routine":"InitPostgres","severity":"FATAL"},"stack":"SequelizeConnectionError: database \"exppost\" does not exist\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:56:32.066Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T08:57:03.183Z"}
info: Connected to the database. {"timestamp":"2024-07-10T08:57:03.448Z"}
info: Server started at http://localhost:3004/api/v1/ {"timestamp":"2024-07-10T09:03:17.297Z"}
info: Connected to the database. {"timestamp":"2024-07-10T09:03:17.386Z"}
